// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spire/api/server/identity/v1/identity.proto

package identity

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	types "github.com/spiffe/spire/proto/spire/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExchangeRequest struct {
	// Types that are valid to be assigned to Step:
	//	*ExchangeRequest_Params_
	//	*ExchangeRequest_ChallengeResponse
	//	*ExchangeRequest_X509Request
	//	*ExchangeRequest_JwtRequest
	Step                 isExchangeRequest_Step `protobuf_oneof:"step"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ExchangeRequest) Reset()         { *m = ExchangeRequest{} }
func (m *ExchangeRequest) String() string { return proto.CompactTextString(m) }
func (*ExchangeRequest) ProtoMessage()    {}
func (*ExchangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_25379ce627d0c156, []int{0}
}

func (m *ExchangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeRequest.Unmarshal(m, b)
}
func (m *ExchangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeRequest.Marshal(b, m, deterministic)
}
func (m *ExchangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeRequest.Merge(m, src)
}
func (m *ExchangeRequest) XXX_Size() int {
	return xxx_messageInfo_ExchangeRequest.Size(m)
}
func (m *ExchangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeRequest proto.InternalMessageInfo

type isExchangeRequest_Step interface {
	isExchangeRequest_Step()
}

type ExchangeRequest_Params_ struct {
	Params *ExchangeRequest_Params `protobuf:"bytes,1,opt,name=params,proto3,oneof"`
}

type ExchangeRequest_ChallengeResponse struct {
	ChallengeResponse []byte `protobuf:"bytes,2,opt,name=challenge_response,json=challengeResponse,proto3,oneof"`
}

type ExchangeRequest_X509Request struct {
	X509Request *X509Request `protobuf:"bytes,3,opt,name=x509Request,proto3,oneof"`
}

type ExchangeRequest_JwtRequest struct {
	JwtRequest *JWTRequest `protobuf:"bytes,4,opt,name=jwtRequest,proto3,oneof"`
}

func (*ExchangeRequest_Params_) isExchangeRequest_Step() {}

func (*ExchangeRequest_ChallengeResponse) isExchangeRequest_Step() {}

func (*ExchangeRequest_X509Request) isExchangeRequest_Step() {}

func (*ExchangeRequest_JwtRequest) isExchangeRequest_Step() {}

func (m *ExchangeRequest) GetStep() isExchangeRequest_Step {
	if m != nil {
		return m.Step
	}
	return nil
}

func (m *ExchangeRequest) GetParams() *ExchangeRequest_Params {
	if x, ok := m.GetStep().(*ExchangeRequest_Params_); ok {
		return x.Params
	}
	return nil
}

func (m *ExchangeRequest) GetChallengeResponse() []byte {
	if x, ok := m.GetStep().(*ExchangeRequest_ChallengeResponse); ok {
		return x.ChallengeResponse
	}
	return nil
}

func (m *ExchangeRequest) GetX509Request() *X509Request {
	if x, ok := m.GetStep().(*ExchangeRequest_X509Request); ok {
		return x.X509Request
	}
	return nil
}

func (m *ExchangeRequest) GetJwtRequest() *JWTRequest {
	if x, ok := m.GetStep().(*ExchangeRequest_JwtRequest); ok {
		return x.JwtRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ExchangeRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ExchangeRequest_Params_)(nil),
		(*ExchangeRequest_ChallengeResponse)(nil),
		(*ExchangeRequest_X509Request)(nil),
		(*ExchangeRequest_JwtRequest)(nil),
	}
}

type ExchangeRequest_Params struct {
	// The exchange data
	Data                 *IdentityExchangeData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ExchangeRequest_Params) Reset()         { *m = ExchangeRequest_Params{} }
func (m *ExchangeRequest_Params) String() string { return proto.CompactTextString(m) }
func (*ExchangeRequest_Params) ProtoMessage()    {}
func (*ExchangeRequest_Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_25379ce627d0c156, []int{0, 0}
}

func (m *ExchangeRequest_Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeRequest_Params.Unmarshal(m, b)
}
func (m *ExchangeRequest_Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeRequest_Params.Marshal(b, m, deterministic)
}
func (m *ExchangeRequest_Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeRequest_Params.Merge(m, src)
}
func (m *ExchangeRequest_Params) XXX_Size() int {
	return xxx_messageInfo_ExchangeRequest_Params.Size(m)
}
func (m *ExchangeRequest_Params) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeRequest_Params.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeRequest_Params proto.InternalMessageInfo

func (m *ExchangeRequest_Params) GetData() *IdentityExchangeData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ExchangeResponse struct {
	// Types that are valid to be assigned to Step:
	//	*ExchangeResponse_X509Result
	//	*ExchangeResponse_JwtResult
	//	*ExchangeResponse_Challenge
	Step                 isExchangeResponse_Step `protobuf_oneof:"step"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ExchangeResponse) Reset()         { *m = ExchangeResponse{} }
func (m *ExchangeResponse) String() string { return proto.CompactTextString(m) }
func (*ExchangeResponse) ProtoMessage()    {}
func (*ExchangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_25379ce627d0c156, []int{1}
}

func (m *ExchangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeResponse.Unmarshal(m, b)
}
func (m *ExchangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeResponse.Marshal(b, m, deterministic)
}
func (m *ExchangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeResponse.Merge(m, src)
}
func (m *ExchangeResponse) XXX_Size() int {
	return xxx_messageInfo_ExchangeResponse.Size(m)
}
func (m *ExchangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeResponse proto.InternalMessageInfo

type isExchangeResponse_Step interface {
	isExchangeResponse_Step()
}

type ExchangeResponse_X509Result struct {
	X509Result *X509Result `protobuf:"bytes,1,opt,name=x509Result,proto3,oneof"`
}

type ExchangeResponse_JwtResult struct {
	JwtResult *JWTResult `protobuf:"bytes,2,opt,name=jwtResult,proto3,oneof"`
}

type ExchangeResponse_Challenge struct {
	Challenge []byte `protobuf:"bytes,3,opt,name=challenge,proto3,oneof"`
}

func (*ExchangeResponse_X509Result) isExchangeResponse_Step() {}

func (*ExchangeResponse_JwtResult) isExchangeResponse_Step() {}

func (*ExchangeResponse_Challenge) isExchangeResponse_Step() {}

func (m *ExchangeResponse) GetStep() isExchangeResponse_Step {
	if m != nil {
		return m.Step
	}
	return nil
}

func (m *ExchangeResponse) GetX509Result() *X509Result {
	if x, ok := m.GetStep().(*ExchangeResponse_X509Result); ok {
		return x.X509Result
	}
	return nil
}

func (m *ExchangeResponse) GetJwtResult() *JWTResult {
	if x, ok := m.GetStep().(*ExchangeResponse_JwtResult); ok {
		return x.JwtResult
	}
	return nil
}

func (m *ExchangeResponse) GetChallenge() []byte {
	if x, ok := m.GetStep().(*ExchangeResponse_Challenge); ok {
		return x.Challenge
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ExchangeResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ExchangeResponse_X509Result)(nil),
		(*ExchangeResponse_JwtResult)(nil),
		(*ExchangeResponse_Challenge)(nil),
	}
}

type RenewRequest struct {
	// Types that are valid to be assigned to Step:
	//	*RenewRequest_X509Request
	//	*RenewRequest_JwtRequest
	Step                 isRenewRequest_Step `protobuf_oneof:"step"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RenewRequest) Reset()         { *m = RenewRequest{} }
func (m *RenewRequest) String() string { return proto.CompactTextString(m) }
func (*RenewRequest) ProtoMessage()    {}
func (*RenewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_25379ce627d0c156, []int{2}
}

func (m *RenewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenewRequest.Unmarshal(m, b)
}
func (m *RenewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenewRequest.Marshal(b, m, deterministic)
}
func (m *RenewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenewRequest.Merge(m, src)
}
func (m *RenewRequest) XXX_Size() int {
	return xxx_messageInfo_RenewRequest.Size(m)
}
func (m *RenewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RenewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RenewRequest proto.InternalMessageInfo

type isRenewRequest_Step interface {
	isRenewRequest_Step()
}

type RenewRequest_X509Request struct {
	X509Request *X509Request `protobuf:"bytes,1,opt,name=x509Request,proto3,oneof"`
}

type RenewRequest_JwtRequest struct {
	JwtRequest *JWTRequest `protobuf:"bytes,2,opt,name=jwtRequest,proto3,oneof"`
}

func (*RenewRequest_X509Request) isRenewRequest_Step() {}

func (*RenewRequest_JwtRequest) isRenewRequest_Step() {}

func (m *RenewRequest) GetStep() isRenewRequest_Step {
	if m != nil {
		return m.Step
	}
	return nil
}

func (m *RenewRequest) GetX509Request() *X509Request {
	if x, ok := m.GetStep().(*RenewRequest_X509Request); ok {
		return x.X509Request
	}
	return nil
}

func (m *RenewRequest) GetJwtRequest() *JWTRequest {
	if x, ok := m.GetStep().(*RenewRequest_JwtRequest); ok {
		return x.JwtRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RenewRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RenewRequest_X509Request)(nil),
		(*RenewRequest_JwtRequest)(nil),
	}
}

type RenewResponse struct {
	// Types that are valid to be assigned to Step:
	//	*RenewResponse_X509Result
	//	*RenewResponse_JwtResult
	Step                 isRenewResponse_Step `protobuf_oneof:"step"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RenewResponse) Reset()         { *m = RenewResponse{} }
func (m *RenewResponse) String() string { return proto.CompactTextString(m) }
func (*RenewResponse) ProtoMessage()    {}
func (*RenewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_25379ce627d0c156, []int{3}
}

func (m *RenewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenewResponse.Unmarshal(m, b)
}
func (m *RenewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenewResponse.Marshal(b, m, deterministic)
}
func (m *RenewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenewResponse.Merge(m, src)
}
func (m *RenewResponse) XXX_Size() int {
	return xxx_messageInfo_RenewResponse.Size(m)
}
func (m *RenewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RenewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RenewResponse proto.InternalMessageInfo

type isRenewResponse_Step interface {
	isRenewResponse_Step()
}

type RenewResponse_X509Result struct {
	X509Result *X509Result `protobuf:"bytes,1,opt,name=x509Result,proto3,oneof"`
}

type RenewResponse_JwtResult struct {
	JwtResult *JWTResult `protobuf:"bytes,2,opt,name=jwtResult,proto3,oneof"`
}

func (*RenewResponse_X509Result) isRenewResponse_Step() {}

func (*RenewResponse_JwtResult) isRenewResponse_Step() {}

func (m *RenewResponse) GetStep() isRenewResponse_Step {
	if m != nil {
		return m.Step
	}
	return nil
}

func (m *RenewResponse) GetX509Result() *X509Result {
	if x, ok := m.GetStep().(*RenewResponse_X509Result); ok {
		return x.X509Result
	}
	return nil
}

func (m *RenewResponse) GetJwtResult() *JWTResult {
	if x, ok := m.GetStep().(*RenewResponse_JwtResult); ok {
		return x.JwtResult
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RenewResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RenewResponse_X509Result)(nil),
		(*RenewResponse_JwtResult)(nil),
	}
}

type X509Request struct {
	Params               *X509Request_X509SVIDParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *X509Request) Reset()         { *m = X509Request{} }
func (m *X509Request) String() string { return proto.CompactTextString(m) }
func (*X509Request) ProtoMessage()    {}
func (*X509Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_25379ce627d0c156, []int{4}
}

func (m *X509Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_X509Request.Unmarshal(m, b)
}
func (m *X509Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_X509Request.Marshal(b, m, deterministic)
}
func (m *X509Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_X509Request.Merge(m, src)
}
func (m *X509Request) XXX_Size() int {
	return xxx_messageInfo_X509Request.Size(m)
}
func (m *X509Request) XXX_DiscardUnknown() {
	xxx_messageInfo_X509Request.DiscardUnknown(m)
}

var xxx_messageInfo_X509Request proto.InternalMessageInfo

func (m *X509Request) GetParams() *X509Request_X509SVIDParams {
	if m != nil {
		return m.Params
	}
	return nil
}

type X509Request_X509SVIDParams struct {
	// Required. The ASN.1 DER encoded Certificate Signing Request (CSR). The
	// CSR is only used to convey the public key; other fields in the CSR are
	// ignored. The X509-SVID attributes are determined by the Server.
	Csr []byte `protobuf:"bytes,1,opt,name=csr,proto3" json:"csr,omitempty"`
	// The desired TTL of the X509-SVID, in seconds. The server default will be
	// used if unset. The TTL is advisory only. The actual lifetime of the
	// X509-SVID may be lower depending on the remaining lifetime of the active
	// SPIRE Server CA.
	Ttl                  int32    `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *X509Request_X509SVIDParams) Reset()         { *m = X509Request_X509SVIDParams{} }
func (m *X509Request_X509SVIDParams) String() string { return proto.CompactTextString(m) }
func (*X509Request_X509SVIDParams) ProtoMessage()    {}
func (*X509Request_X509SVIDParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_25379ce627d0c156, []int{4, 0}
}

func (m *X509Request_X509SVIDParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_X509Request_X509SVIDParams.Unmarshal(m, b)
}
func (m *X509Request_X509SVIDParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_X509Request_X509SVIDParams.Marshal(b, m, deterministic)
}
func (m *X509Request_X509SVIDParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_X509Request_X509SVIDParams.Merge(m, src)
}
func (m *X509Request_X509SVIDParams) XXX_Size() int {
	return xxx_messageInfo_X509Request_X509SVIDParams.Size(m)
}
func (m *X509Request_X509SVIDParams) XXX_DiscardUnknown() {
	xxx_messageInfo_X509Request_X509SVIDParams.DiscardUnknown(m)
}

var xxx_messageInfo_X509Request_X509SVIDParams proto.InternalMessageInfo

func (m *X509Request_X509SVIDParams) GetCsr() []byte {
	if m != nil {
		return m.Csr
	}
	return nil
}

func (m *X509Request_X509SVIDParams) GetTtl() int32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

type JWTRequest struct {
	Params               *JWTRequest_JWTSVIDParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *JWTRequest) Reset()         { *m = JWTRequest{} }
func (m *JWTRequest) String() string { return proto.CompactTextString(m) }
func (*JWTRequest) ProtoMessage()    {}
func (*JWTRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_25379ce627d0c156, []int{5}
}

func (m *JWTRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JWTRequest.Unmarshal(m, b)
}
func (m *JWTRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JWTRequest.Marshal(b, m, deterministic)
}
func (m *JWTRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JWTRequest.Merge(m, src)
}
func (m *JWTRequest) XXX_Size() int {
	return xxx_messageInfo_JWTRequest.Size(m)
}
func (m *JWTRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JWTRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JWTRequest proto.InternalMessageInfo

func (m *JWTRequest) GetParams() *JWTRequest_JWTSVIDParams {
	if m != nil {
		return m.Params
	}
	return nil
}

type JWTRequest_JWTSVIDParams struct {
	// Required. List of audience claims to include in the JWT-SVID.
	// At least one must be set.
	Audience []string `protobuf:"bytes,1,rep,name=audience,proto3" json:"audience,omitempty"`
	// Desired TTL of the JWT-SVID, in seconds. The server default will be used
	// if unset. The TTL is advisory only. The actual lifetime of the JWT-SVID
	// may be lower depending on the remaining lifetime of the active SPIRE
	// Server CA.
	Ttl                  int32    `protobuf:"varint,2,opt,name=Ttl,proto3" json:"Ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JWTRequest_JWTSVIDParams) Reset()         { *m = JWTRequest_JWTSVIDParams{} }
func (m *JWTRequest_JWTSVIDParams) String() string { return proto.CompactTextString(m) }
func (*JWTRequest_JWTSVIDParams) ProtoMessage()    {}
func (*JWTRequest_JWTSVIDParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_25379ce627d0c156, []int{5, 0}
}

func (m *JWTRequest_JWTSVIDParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JWTRequest_JWTSVIDParams.Unmarshal(m, b)
}
func (m *JWTRequest_JWTSVIDParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JWTRequest_JWTSVIDParams.Marshal(b, m, deterministic)
}
func (m *JWTRequest_JWTSVIDParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JWTRequest_JWTSVIDParams.Merge(m, src)
}
func (m *JWTRequest_JWTSVIDParams) XXX_Size() int {
	return xxx_messageInfo_JWTRequest_JWTSVIDParams.Size(m)
}
func (m *JWTRequest_JWTSVIDParams) XXX_DiscardUnknown() {
	xxx_messageInfo_JWTRequest_JWTSVIDParams.DiscardUnknown(m)
}

var xxx_messageInfo_JWTRequest_JWTSVIDParams proto.InternalMessageInfo

func (m *JWTRequest_JWTSVIDParams) GetAudience() []string {
	if m != nil {
		return m.Audience
	}
	return nil
}

func (m *JWTRequest_JWTSVIDParams) GetTtl() int32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

//  TODO: Move to spire.types
type IdentityExchangeData struct {
	// The type of the identity exchange data.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// The exchanging data payload. For JWT it must include
	Payload              string   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdentityExchangeData) Reset()         { *m = IdentityExchangeData{} }
func (m *IdentityExchangeData) String() string { return proto.CompactTextString(m) }
func (*IdentityExchangeData) ProtoMessage()    {}
func (*IdentityExchangeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_25379ce627d0c156, []int{6}
}

func (m *IdentityExchangeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityExchangeData.Unmarshal(m, b)
}
func (m *IdentityExchangeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityExchangeData.Marshal(b, m, deterministic)
}
func (m *IdentityExchangeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityExchangeData.Merge(m, src)
}
func (m *IdentityExchangeData) XXX_Size() int {
	return xxx_messageInfo_IdentityExchangeData.Size(m)
}
func (m *IdentityExchangeData) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityExchangeData.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityExchangeData proto.InternalMessageInfo

func (m *IdentityExchangeData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *IdentityExchangeData) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type X509Result struct {
	Svid                 *types.X509SVID `protobuf:"bytes,1,opt,name=svid,proto3" json:"svid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *X509Result) Reset()         { *m = X509Result{} }
func (m *X509Result) String() string { return proto.CompactTextString(m) }
func (*X509Result) ProtoMessage()    {}
func (*X509Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_25379ce627d0c156, []int{7}
}

func (m *X509Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_X509Result.Unmarshal(m, b)
}
func (m *X509Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_X509Result.Marshal(b, m, deterministic)
}
func (m *X509Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_X509Result.Merge(m, src)
}
func (m *X509Result) XXX_Size() int {
	return xxx_messageInfo_X509Result.Size(m)
}
func (m *X509Result) XXX_DiscardUnknown() {
	xxx_messageInfo_X509Result.DiscardUnknown(m)
}

var xxx_messageInfo_X509Result proto.InternalMessageInfo

func (m *X509Result) GetSvid() *types.X509SVID {
	if m != nil {
		return m.Svid
	}
	return nil
}

type JWTResult struct {
	Svid                 *types.JWTSVID `protobuf:"bytes,1,opt,name=svid,proto3" json:"svid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *JWTResult) Reset()         { *m = JWTResult{} }
func (m *JWTResult) String() string { return proto.CompactTextString(m) }
func (*JWTResult) ProtoMessage()    {}
func (*JWTResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_25379ce627d0c156, []int{8}
}

func (m *JWTResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JWTResult.Unmarshal(m, b)
}
func (m *JWTResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JWTResult.Marshal(b, m, deterministic)
}
func (m *JWTResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JWTResult.Merge(m, src)
}
func (m *JWTResult) XXX_Size() int {
	return xxx_messageInfo_JWTResult.Size(m)
}
func (m *JWTResult) XXX_DiscardUnknown() {
	xxx_messageInfo_JWTResult.DiscardUnknown(m)
}

var xxx_messageInfo_JWTResult proto.InternalMessageInfo

func (m *JWTResult) GetSvid() *types.JWTSVID {
	if m != nil {
		return m.Svid
	}
	return nil
}

func init() {
	proto.RegisterType((*ExchangeRequest)(nil), "spire.api.server.identity.v1.ExchangeRequest")
	proto.RegisterType((*ExchangeRequest_Params)(nil), "spire.api.server.identity.v1.ExchangeRequest.Params")
	proto.RegisterType((*ExchangeResponse)(nil), "spire.api.server.identity.v1.ExchangeResponse")
	proto.RegisterType((*RenewRequest)(nil), "spire.api.server.identity.v1.RenewRequest")
	proto.RegisterType((*RenewResponse)(nil), "spire.api.server.identity.v1.RenewResponse")
	proto.RegisterType((*X509Request)(nil), "spire.api.server.identity.v1.X509Request")
	proto.RegisterType((*X509Request_X509SVIDParams)(nil), "spire.api.server.identity.v1.X509Request.X509SVIDParams")
	proto.RegisterType((*JWTRequest)(nil), "spire.api.server.identity.v1.JWTRequest")
	proto.RegisterType((*JWTRequest_JWTSVIDParams)(nil), "spire.api.server.identity.v1.JWTRequest.JWTSVIDParams")
	proto.RegisterType((*IdentityExchangeData)(nil), "spire.api.server.identity.v1.IdentityExchangeData")
	proto.RegisterType((*X509Result)(nil), "spire.api.server.identity.v1.X509Result")
	proto.RegisterType((*JWTResult)(nil), "spire.api.server.identity.v1.JWTResult")
}

func init() {
	proto.RegisterFile("spire/api/server/identity/v1/identity.proto", fileDescriptor_25379ce627d0c156)
}

var fileDescriptor_25379ce627d0c156 = []byte{
	// 627 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xee, 0x36, 0x69, 0x88, 0x27, 0x29, 0x94, 0x55, 0x91, 0x82, 0x85, 0x50, 0xe4, 0x0b, 0x2e,
	0x15, 0x76, 0x1b, 0x5a, 0x7e, 0x84, 0xb8, 0x94, 0x14, 0xd2, 0x48, 0xa0, 0x68, 0x89, 0x00, 0x71,
	0x81, 0x6d, 0xb2, 0x4d, 0x5c, 0x39, 0x8e, 0xf1, 0x6e, 0x92, 0xe6, 0x09, 0x78, 0x02, 0x4e, 0xbc,
	0x02, 0x17, 0x9e, 0x84, 0x07, 0xe0, 0x65, 0x90, 0xd7, 0x6b, 0x3b, 0x09, 0x95, 0x65, 0x04, 0x07,
	0x6e, 0x13, 0xcf, 0x7c, 0xdf, 0x7e, 0x33, 0x5f, 0x66, 0x17, 0x76, 0xb9, 0xef, 0x04, 0xcc, 0xa6,
	0xbe, 0x63, 0x73, 0x16, 0x4c, 0x59, 0x60, 0x3b, 0x7d, 0xe6, 0x09, 0x47, 0xcc, 0xed, 0xe9, 0x7e,
	0x12, 0x5b, 0x7e, 0x30, 0x16, 0x63, 0x7c, 0x4b, 0x16, 0x5b, 0xd4, 0x77, 0xac, 0xa8, 0xd8, 0x4a,
	0x0a, 0xa6, 0xfb, 0xba, 0x1e, 0x51, 0x89, 0xb9, 0xcf, 0xb8, 0x7d, 0x71, 0xb8, 0xf7, 0x98, 0x4f,
	0x9d, 0x7e, 0x84, 0xd4, 0x6f, 0x2e, 0xe6, 0xce, 0x67, 0x22, 0x4d, 0x19, 0x9f, 0x0b, 0x70, 0xed,
	0xf8, 0xa2, 0x37, 0xa4, 0xde, 0x80, 0x11, 0xf6, 0x69, 0xc2, 0xb8, 0xc0, 0xaf, 0xa0, 0xe4, 0xd3,
	0x80, 0x8e, 0x78, 0x0d, 0xd5, 0x91, 0x59, 0x69, 0x1c, 0x58, 0x59, 0x27, 0x5b, 0x2b, 0x70, 0xab,
	0x23, 0xb1, 0xad, 0x35, 0xa2, 0x58, 0xb0, 0x0d, 0xb8, 0x37, 0xa4, 0xae, 0xcb, 0xbc, 0x01, 0xfb,
	0x10, 0x30, 0xee, 0x8f, 0x3d, 0xce, 0x6a, 0xeb, 0x75, 0x64, 0x56, 0x5b, 0x6b, 0xe4, 0x7a, 0x92,
	0x23, 0x2a, 0x85, 0x5f, 0x42, 0x25, 0xec, 0x40, 0x11, 0xd6, 0x0a, 0x52, 0xc5, 0x4e, 0xb6, 0x8a,
	0x77, 0x29, 0xa0, 0xb5, 0x46, 0x16, 0xf1, 0xb8, 0x0d, 0x70, 0x3e, 0x13, 0x31, 0x5b, 0x51, 0xb2,
	0x99, 0xd9, 0x6c, 0xed, 0xb7, 0xdd, 0x94, 0x6c, 0x01, 0xad, 0x77, 0xa0, 0x14, 0xf5, 0x87, 0x9f,
	0x43, 0xb1, 0x4f, 0x05, 0x55, 0x33, 0x6a, 0x64, 0xf3, 0x9d, 0xa8, 0x38, 0x9e, 0x55, 0x93, 0x0a,
	0x4a, 0x24, 0xfe, 0xa8, 0x04, 0x45, 0x2e, 0x98, 0x6f, 0xfc, 0x40, 0xb0, 0x95, 0x8e, 0x52, 0x4d,
	0xa2, 0x0d, 0x10, 0x75, 0xc2, 0x27, 0xae, 0x50, 0x47, 0x99, 0x79, 0x06, 0x11, 0xd6, 0x87, 0xd2,
	0x53, 0x34, 0x7e, 0x01, 0x9a, 0x6c, 0x44, 0x52, 0xad, 0x4b, 0xaa, 0x3b, 0x39, 0xa6, 0xa0, 0x98,
	0x52, 0x2c, 0xbe, 0x0d, 0x5a, 0xe2, 0x99, 0x34, 0x27, 0xb4, 0x31, 0xfd, 0x94, 0x74, 0xf4, 0x1d,
	0x41, 0x95, 0x30, 0x8f, 0xcd, 0x62, 0x23, 0x56, 0x7c, 0x45, 0xff, 0xd4, 0xd7, 0xf5, 0xbf, 0xf1,
	0x35, 0xd1, 0xfc, 0x0d, 0xc1, 0xa6, 0xd2, 0xfc, 0x1f, 0x5b, 0x90, 0xc8, 0xfd, 0x82, 0xa0, 0xb2,
	0x30, 0x21, 0xdc, 0x59, 0x59, 0xdd, 0x47, 0xb9, 0x87, 0x2b, 0xe3, 0xd7, 0x6f, 0x4e, 0x9a, 0xd1,
	0xdf, 0x3b, 0x5e, 0x5e, 0xfd, 0x00, 0xae, 0x2e, 0x67, 0xf0, 0x16, 0x14, 0x7a, 0x3c, 0x90, 0x07,
	0x54, 0x49, 0x18, 0x86, 0x5f, 0x84, 0x70, 0x65, 0x43, 0x1b, 0x24, 0x0c, 0x8d, 0xaf, 0x08, 0x20,
	0x9d, 0xf5, 0x6f, 0x37, 0xca, 0x83, 0xbc, 0x2e, 0x85, 0xe1, 0x25, 0xa2, 0x9e, 0xc2, 0xe6, 0x52,
	0x02, 0xeb, 0x50, 0xa6, 0x93, 0xbe, 0xc3, 0xbc, 0x1e, 0xab, 0xa1, 0x7a, 0xc1, 0xd4, 0x48, 0xf2,
	0x3b, 0x54, 0xd7, 0x4d, 0xd5, 0x75, 0x85, 0x6b, 0x34, 0x61, 0xfb, 0xb2, 0x85, 0xc4, 0x18, 0x8a,
	0xe1, 0x1d, 0x29, 0x45, 0x6a, 0x44, 0xc6, 0xb8, 0x06, 0x57, 0x7c, 0x3a, 0x77, 0xc7, 0xb4, 0x2f,
	0x19, 0x34, 0x12, 0xff, 0x34, 0x1e, 0x02, 0xa4, 0x46, 0xe3, 0x1d, 0x28, 0x86, 0xd7, 0xaa, 0x6a,
	0xf0, 0x86, 0x6a, 0x50, 0x5e, 0xb9, 0xc9, 0x68, 0x89, 0x2c, 0x31, 0x0e, 0x41, 0x4b, 0x6c, 0xc5,
	0xe6, 0x12, 0x6e, 0x7b, 0x09, 0xa7, 0x7a, 0x8c, 0x60, 0x8d, 0x9f, 0x08, 0xca, 0xb1, 0x6c, 0x3c,
	0x82, 0x72, 0x2c, 0x1d, 0xdf, 0xfb, 0xa3, 0xfb, 0x59, 0xb7, 0xf2, 0x96, 0x47, 0x0b, 0x60, 0xa2,
	0x3d, 0x84, 0x3f, 0xc2, 0x86, 0xdc, 0x0a, 0x7c, 0x37, 0x1b, 0xbc, 0xb8, 0xee, 0xfa, 0x6e, 0xae,
	0xda, 0xe8, 0x94, 0xa3, 0xe3, 0xf7, 0xcf, 0x06, 0x8e, 0x18, 0x4e, 0x4e, 0xad, 0xde, 0x78, 0x64,
	0x73, 0xdf, 0x39, 0x3b, 0x63, 0x76, 0xf4, 0x6e, 0xc9, 0x97, 0xca, 0xce, 0x7a, 0x2a, 0x9f, 0xc4,
	0xf1, 0x69, 0x49, 0x16, 0xdf, 0xff, 0x15, 0x00, 0x00, 0xff, 0xff, 0x31, 0x71, 0x68, 0x2c, 0x5a,
	0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IdentityClient is the client API for Identity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IdentityClient interface {
	// Exchanges a platform-specific identity document with an SVID.
	// A bidirectional stream is provided to facilitate the exchange methods
	// that require challenge/response. The result can be an X509 SVID or a JWT-SVID.
	Exchange(ctx context.Context, opts ...grpc.CallOption) (Identity_ExchangeClient, error)
	// Renews the current SVID returning a new SVID. The new SVID is not enabled
	// on the server side until its first use.
	//
	// The caller must present an active SVID, i.e. the SVID
	// returned by the Exchange or the most recent Renew call.
	Renew(ctx context.Context, in *RenewRequest, opts ...grpc.CallOption) (*RenewResponse, error)
}

type identityClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityClient(cc grpc.ClientConnInterface) IdentityClient {
	return &identityClient{cc}
}

func (c *identityClient) Exchange(ctx context.Context, opts ...grpc.CallOption) (Identity_ExchangeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Identity_serviceDesc.Streams[0], "/spire.api.server.identity.v1.Identity/Exchange", opts...)
	if err != nil {
		return nil, err
	}
	x := &identityExchangeClient{stream}
	return x, nil
}

type Identity_ExchangeClient interface {
	Send(*ExchangeRequest) error
	Recv() (*ExchangeResponse, error)
	grpc.ClientStream
}

type identityExchangeClient struct {
	grpc.ClientStream
}

func (x *identityExchangeClient) Send(m *ExchangeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *identityExchangeClient) Recv() (*ExchangeResponse, error) {
	m := new(ExchangeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *identityClient) Renew(ctx context.Context, in *RenewRequest, opts ...grpc.CallOption) (*RenewResponse, error) {
	out := new(RenewResponse)
	err := c.cc.Invoke(ctx, "/spire.api.server.identity.v1.Identity/Renew", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServer is the server API for Identity service.
type IdentityServer interface {
	// Exchanges a platform-specific identity document with an SVID.
	// A bidirectional stream is provided to facilitate the exchange methods
	// that require challenge/response. The result can be an X509 SVID or a JWT-SVID.
	Exchange(Identity_ExchangeServer) error
	// Renews the current SVID returning a new SVID. The new SVID is not enabled
	// on the server side until its first use.
	//
	// The caller must present an active SVID, i.e. the SVID
	// returned by the Exchange or the most recent Renew call.
	Renew(context.Context, *RenewRequest) (*RenewResponse, error)
}

// UnimplementedIdentityServer can be embedded to have forward compatible implementations.
type UnimplementedIdentityServer struct {
}

func (*UnimplementedIdentityServer) Exchange(srv Identity_ExchangeServer) error {
	return status.Errorf(codes.Unimplemented, "method Exchange not implemented")
}
func (*UnimplementedIdentityServer) Renew(ctx context.Context, req *RenewRequest) (*RenewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Renew not implemented")
}

func RegisterIdentityServer(s *grpc.Server, srv IdentityServer) {
	s.RegisterService(&_Identity_serviceDesc, srv)
}

func _Identity_Exchange_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IdentityServer).Exchange(&identityExchangeServer{stream})
}

type Identity_ExchangeServer interface {
	Send(*ExchangeResponse) error
	Recv() (*ExchangeRequest, error)
	grpc.ServerStream
}

type identityExchangeServer struct {
	grpc.ServerStream
}

func (x *identityExchangeServer) Send(m *ExchangeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *identityExchangeServer) Recv() (*ExchangeRequest, error) {
	m := new(ExchangeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Identity_Renew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).Renew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spire.api.server.identity.v1.Identity/Renew",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).Renew(ctx, req.(*RenewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Identity_serviceDesc = grpc.ServiceDesc{
	ServiceName: "spire.api.server.identity.v1.Identity",
	HandlerType: (*IdentityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Renew",
			Handler:    _Identity_Renew_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exchange",
			Handler:       _Identity_Exchange_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "spire/api/server/identity/v1/identity.proto",
}
