#!/bin/bash

log-debug "creating leafA downstream registration entry..."
# Create downstream registation entry on intermediateA-server for `leafA-server`
docker-compose exec -T intermediateA-server \
    /opt/spire/bin/spire-server entry create \
    -parentID "spiffe://domain.test/spire/agent/x509pop/$(fingerprint intermediateA/agent/agent.crt.pem)" \
    -spiffeID "spiffe://domain.test/leafA" \
    -selector "docker:label:org.integration.name:leafA" \
    -downstream \
    -ttl 90

# Check at most 30 times (with one second in between) that the agent has
# successfully synced down the workload entry.
MAXCHECKS=30
CHECKINTERVAL=1
for ((i=1;i<=MAXCHECKS;i++)); do
    log-info "checking for synced workload entry ($i of $MAXCHECKS max)..."
    docker-compose logs intermediateA-agent
    if docker-compose logs intermediateA-agent | grep "spiffe://domain.test/leafA"; then
        exit 0
    fi
    sleep "${CHECKINTERVAL}"
done

fail-now "timed out waiting for agent to sync down entry"



