#!/bin/bash

log-debug "creating leafB downstream registration entry..."
# Create downstream registration entry on itermediateB for leafB-server
docker-compose exec -T intermediateB-server \
    /opt/spire/bin/spire-server entry create \
    -parentID "spiffe://domain.test/spire/agent/x509pop/$(fingerprint intermediateB/agent/agent.crt.pem)" \
    -spiffeID "spiffe://domain.test/leafB" \
    -selector "docker:label:org.integration.name:leafB" \
    -downstream \
    -ttl 90

# Check at most 30 times (with one second in between) that the agent has
# successfully synced down the workload entry.
MAXCHECKS=30
CHECKINTERVAL=1
for ((i=1;i<=MAXCHECKS;i++)); do
    log-info "checking for synced workload entry ($i of $MAXCHECKS max)..."
    docker-compose logs intermediateB-agent
    if docker-compose logs intermediateB-agent | grep "spiffe://domain.test/leafB"; then
        exit 0
    fi
    sleep "${CHECKINTERVAL}"
done

fail-now "timed out waiting for agent to sync down entry"



